name: Bot TikTok Auto-Pilot

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - run-bot

  schedule:
    # 02:00 UTC = 09:00 WIB
    - cron: '0 2 * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Bersihkan Workspace
        run: |
          rm -rf temp/*
          rm -rf output/*
          mkdir -p temp output assets/fonts

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Jalankan Bot
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_API_KEY_1: ${{ secrets.GEMINI_API_KEY_1 }}
          GEMINI_API_KEY_2: ${{ secrets.GEMINI_API_KEY_2 }}
          GEMINI_API_KEY_3: ${{ secrets.GEMINI_API_KEY_3 }}
          GEMINI_API_KEY_4: ${{ secrets.GEMINI_API_KEY_4 }}
          GEMINI_API_KEY_5: ${{ secrets.GEMINI_API_KEY_5 }}
          GEMINI_API_KEY_6: ${{ secrets.GEMINI_API_KEY_6 }}
          GEMINI_API_KEY_7: ${{ secrets.GEMINI_API_KEY_7 }}
          GEMINI_API_KEY_8: ${{ secrets.GEMINI_API_KEY_8 }}
        run: |
          python app.py

      - name: Lihat Hasil Output
        if: always()
        run: |
          echo "Isi folder output:"
          ls -lah output || true

      - name: Kirim Hasil Video ke Telegram Bot
        if: success()
        run: |
          VIDEO_FILE=$(ls output/*.mp4 | head -n 1)
          
          if [ -z "$VIDEO_FILE" ]; then
            echo "❌ Eror: Tidak ada file video .mp4 di folder output!"
            exit 1
          fi
          
          echo "🚀 Mengirim $VIDEO_FILE ke Telegram..."
          
          curl -v -F video="@${VIDEO_FILE}" \
            -F caption="✅ Video Ruang Pikir Berhasil Dirender Sempurna!" \
            "https://api.telegram.org/bot8644685615:AAERnJkiFVLR0HhFxmj5HTFmYhsmtytso1A/sendVideo?chat_id=1120755820"

      - name: Upload Hasil Video
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: video-tiktok-fakta
          path: output/
          retention-days: 7
